#!/usr/bin/env python3
"""gitignore —— 离线生成 .gitignore 文件的小工具。

纯标准库，模板内置，无需联网。
"""

import argparse
import difflib
import sys

VERSION = "0.1.0"

# 模板：名字 -> (描述, 忽略条目)
TEMPLATES = {
    "python": (
        "Python",
        """\
# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# Virtual environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

# Testing & coverage
.tox/
.nox/
.coverage
.coverage.*
.cache
.pytest_cache/
htmlcov/
nosetests.xml
coverage.xml
*.cover
*.py,cover
.hypothesis/

# Type checkers
.mypy_cache/
.dmypy.json
dmypy.json
.pyre/
.pytype/

# Jupyter
.ipynb_checkpoints

# Installer logs
pip-log.txt
pip-delete-this-directory.txt
""",
    ),
    "node": (
        "Node.js",
        """\
# Logs
logs/
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*
.pnpm-debug.log*

# Dependencies
node_modules/
.jspm_packages/

# Build output
dist/
build/
out/
.next/
.nuxt/
.turbo

# Runtime data
pids/
*.pid
*.seed
*.pid.lock

# Coverage
coverage/
*.lcov
.nyc_output/

# Test snapshots that churn
# (keep __snapshots__ if you want them)

# Caches
.npm/
.eslintcache
.parcel-cache/
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/
.node_repl_history
*.tsbuildinfo
.vite/

# dotenv environment files (keep .env.example)
.env
.env*.local

# Misc
.DS_Store
""",
    ),
    "java": (
        "Java",
        """\
# Compiled class files
*.class

# Log files
*.log

# Package files
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar

# Build directories
target/
build/
out/
bin/

# Maven
.mvn/
mvnw
mvnw.cmd

# Gradle
.gradle/
gradle-app.setting
!gradle-wrapper.jar
!gradle-wrapper.properties

# IDE handled by their own templates, plus:
*.iml

# Virtual machine crash logs
hs_err_pid*
replay_pid*
""",
    ),
    "go": (
        "Go",
        """\
# Binaries
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary, built with `go test -c`
*.test

# Output of the go coverage tool
*.out

# Build output
/bin/
/dist/

# Dependency directories (keep go.sum committed)
/vendor/

# Go workspace file
go.work
go.work.sum

# Editor / IDE
.idea/
.vscode/
*.swp
""",
    ),
    "rust": (
        "Rust",
        """\
# Generated by Cargo
/target/
**/*.rs.bk

# Cargo lock for libraries (keep it for binaries)
# Cargo.lock

# Backup files
*.orig

# MSVC Windows builds
*.pdb

# Editor / IDE
.idea/
.vscode/
*.swp
""",
    ),
    "macos": (
        "macOS",
        """\
# General
.DS_Store
.AppleDouble
.LSOverride

# Icon must end with two \\r
Icon

# Thumbnails
._*

# Files that might appear in the root of a volume
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
.com.apple.timemachine.donotpresent

# Directories potentially created on remote AFP share
.AppleDB
.AppleDesktop
Network Trash Folder
Temporary Items
.apdisk
""",
    ),
    "windows": (
        "Windows",
        """\
# Windows thumbnail cache files
Thumbs.db
Thumbs.db:encryptable
ehthumbs.db
ehthumbs_vista.db

# Dump file
*.stackdump

# Folder config file
[Dd]esktop.ini

# Recycle Bin used on file shares
$RECYCLE.BIN/

# Windows Installer files
*.cab
*.msi
*.msix
*.msm
*.msp

# Windows shortcuts
*.lnk

# NTFS alternate data streams artifacts
:Zone.Identifier
""",
    ),
    "linux": (
        "Linux",
        """\
# Temporary files
*~

# KDE directory preferences
.directory

# Linux trash folder which might appear on any partition or disk
.Trash-*

# .nfs files are created when an open file is removed but is still
# being accessed (common on NFS mounts)
.nfs*
""",
    ),
    "vscode": (
        "Visual Studio Code",
        """\
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
!.vscode/*.code-snippets

# Local History for Visual Studio Code
.history/

# Built Visual Studio Code Extensions
*.vsix
""",
    ),
    "jetbrains": (
        "JetBrains IDEs",
        """\
# Covers JetBrains IDEs: IntelliJ, RubyMine, PhpStorm, AppCode,
# PyCharm, CLion, Android Studio, WebStorm and Rider
.idea/

# CMake
cmake-build-*/

# Mongo Explorer plugin
.idea/mongoSettings.xml

# File-based project format
*.iws

# IntelliJ
out/

# mpeltonen/sbt-idea plugin
.idea_modules/

# JIRA plugin
atlassian-ide-plugin.xml

# Cursive Clojure plugin
.idea/replstate.xml

# Crashlytics plugin (for Android Studio and IntelliJ)
com_crashlytics_export_strings.xml
crashlytics.properties
crashlytics-build.properties
fabric.properties

# Editor-based Rest Client
.idea/httpRequests

# Android studio 3.1+ serialized cache file
.idea/caches/build_file_checksums.ser
""",
    ),
}

ORDER = ["python", "node", "java", "go", "rust", "macos", "windows", "linux", "vscode", "jetbrains"]


def render(stacks):
    """Render combined .gitignore text for the given stack names."""
    parts = []
    for name in stacks:
        desc, body = TEMPLATES[name]
        parts.append(f"### {desc} ###\n{body.rstrip()}\n")
    return "\n".join(parts)


def suggest(name):
    matches = difflib.get_close_matches(name, TEMPLATES.keys(), n=1, cutoff=0.6)
    if matches:
        return f"（你是不是想找：{matches[0]}？）"
    return ""


def cmd_list(args):
    for name in ORDER:
        desc, _ = TEMPLATES[name]
        print(f"{name:12s} {desc}")
    return 0


def cmd_generate(args):
    stacks = []
    for name in args.stacks:
        key = name.lower()
        if key not in TEMPLATES:
            print(f"error: 未知的模板：{name} {suggest(key)}", file=sys.stderr)
            print("用 `gitignore --list` 查看可用模板。", file=sys.stderr)
            return 1
        if key not in stacks:
            stacks.append(key)
    text = render(stacks)

    target = args.write
    if target is None and not args.append:
        # stdout 模式
        sys.stdout.write(text)
        return 0

    path = args.write or ".gitignore"
    mode = "a" if args.append else "w"
    if mode == "w":
        import os

        if os.path.exists(path) and not args.force:
            print(
                f"error: {path} 已存在，不会覆盖。用 --force 覆盖，或用 --append 追加。",
                file=sys.stderr,
            )
            return 1
    with open(path, mode, encoding="utf-8") as f:
        if mode == "a":
            f.write("\n")
        f.write(text)
    action = "追加到" if mode == "a" else "写入"
    print(f"已{action} {path}（{len(stacks)} 个模板：{', '.join(stacks)}）")
    return 0


def build_parser():
    p = argparse.ArgumentParser(
        prog="gitignore",
        description="离线生成 .gitignore：gitignore python node（纯本地，无需联网）",
    )
    p.add_argument("--version", action="version", version=f"%(prog)s {VERSION}")
    p.add_argument("--list", action="store_true", help="列出所有可用模板")
    p.add_argument("--write", nargs="?", const=".gitignore", metavar="PATH",
                   help="写入文件（默认 ./.gitignore）；已存在时拒绝覆盖")
    p.add_argument("--append", action="store_true", help="追加到 ./.gitignore 而不是输出到 stdout")
    p.add_argument("--force", action="store_true", help="--write 时允许覆盖已存在的文件")
    p.add_argument("stacks", nargs="*", help="模板名，如 python node（可多个）")
    return p


def main(argv=None):
    args = build_parser().parse_args(argv)
    if args.list:
        return cmd_list(args)
    if not args.stacks:
        print("error: 请指定至少一个模板，例如：gitignore python node", file=sys.stderr)
        print("用 `gitignore --list` 查看可用模板。", file=sys.stderr)
        return 2
    return cmd_generate(args)


if __name__ == "__main__":
    sys.exit(main())
